version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
    - 80:80
    environment:
      # Do not forget that any $variable must be escaped
      # with extra 'dollar' (e.g. $$variable). Otherwise it
      # will be substituted by docker-compose.
      CONFIG: |
        server {
          listen 80;

          location / {
            # Print the URL you're visiting
            add_header Content-Type text/plain;
            return 200 "URL: $$uri";
          }
        }
    entrypoint:
      - /bin/ash
      - -c
    command:
      - echo "$$CONFIG" > /etc/nginx/conf.d/default.conf && /docker-entrypoint.sh nginx -g "daemon off;"

    # Not supported in Docker Desktop on Mac OS and Windows
    #network_mode: host
