version: "3.7"

services:
  nginx:
    build:
      context: ./image
    ports:
    - 80:80
    volumes:
    # Main config file
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    # Include files from conf.d
    - ./config/conf.d:/etc/nginx/conf.d

    # Not supported in Docker Desktop on Mac OS and Windows
    #network_mode: host
